steps:
  # Step 1: Clone GitHub repo
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/chandranajith29/DEMO_REP.git repo
        cd repo
        echo "Repository cloned successfully."

  # Step 2: Copy desired files to GCS bucket
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Uploading files to GCS bucket..."
        gsutil -m cp -r repo/<gcs_to_bq_and_bq_operators.py> ${_BUCKET_PATH}
        echo "Upload complete."

substitutions:
  _BUCKET_PATH: gs://us-central1-composer1-1c4a17c9-bucket/dags

options:
  logging: CLOUD_LOGGING_ONLY
