BEGIN TRANSACTION;

ALTER SESSION SET TIMEZONE = 'EST';

COPY INTO NEXUS_DATAPLATFORM.P_MVPD.P_NEXUS_MVPD_SPECTRUM_STG
FROM @NEXUS_DATAPLATFORM.P_MVPD.NEXUS_MVPD_SPECTRUM_PRD/preprocessing/
FILE_FORMAT = (TYPE = CSV, FIELD_OPTIONALLY_ENCLOSED_BY='"', PARSE_HEADER = TRUE, ERROR_ON_COLUMN_COUNT_MISMATCH = false)
PATTERN = '.*\\.csv'
ON_ERROR = 'CONTINUE'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
INCLUDE_METADATA = (
FILE_NAME = METADATA$FILENAME,
INSERTION_DATETIME = METADATA$START_SCAN_TIME);

COMMIT;