BEGIN;

-- Step 1: Delete Existing Records
DELETE FROM NEXUS_DATAPLATFORM.P_MVPD.P_NEXUS_MVPD_SPECTRUM
WHERE
  date IN (
  SELECT
    DISTINCT date
  FROM
    NEXUS_DATAPLATFORM.P_MVPD.P_NEXUS_MVPD_SPECTRUM_STG
    );

-- Step 2: Insert New Data
INSERT INTO NEXUS_DATAPLATFORM.P_MVPD.P_NEXUS_MVPD_SPECTRUM
SELECT * FROM NEXUS_DATAPLATFORM.P_MVPD.P_NEXUS_MVPD_SPECTRUM_STG;

-- Step 3: Insert into Log Table
INSERT INTO NEXUS_DATAPLATFORM.P_MVPD.P_NEXUS_MVPD_SPECTRUM_DMA_LOG
SELECT DISTINCT
    insertion_order,
    date AS event_date,
    file_name,
    INSERTION_DATETIME
FROM NEXUS_DATAPLATFORM.P_MVPD.P_NEXUS_MVPD_SPECTRUM_STG
WHERE edi_order_number IS NULL;

COMMIT;