configs:
  monitoring:
    file: monitoring/checks_all.yaml
  sub_dags:
    pds:
      


      - dag_id: "mvpd_data.mvpd_spectrum"
        tags: ["mvpd", "spectrum", "prod"]
        input_bucket: "spectrum-landing"
        source_file:
          storage_type: "gcs"
          prefix: "inbound/"
          file_pattern: "inbound/Nexus Monday Detail Reporting*"
          dttm_pattern: ""
          field_delimiter: ","
          quote_character: '"'
          skip_leading_rows: 1
          gcs_sensor_poke_interval: 10
          gcs_sensor_timeout: 30
          is_excel: False
          skip_if_no_files: True
          ignore_date_check: True
          fileprocessday: { "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY" ,"SUNDAY"}
        staging_table:
          name: "${project_id}.mvpd_data.mvpd_spectrum_stg"
          load_method: "WRITE_TRUNCATE"
        pds_load_sql_path: "mvpd_spectrum.sql"
        aggregation_tables:
          mvpd_dma: "mvpd_spectrum_dma_agg.sql"
          mvpd_network: "mvpd_spectrum_network_agg.sql"
          mvpd_lineitem: "mvpd_spectrum_line_item_agg.sql"

        skip_source_file_ingestion: False
        data_check:
          data_check_flag: True
          data_check_sql_path : "spectrum.sql"
        snowflake_active: True
        snowflake:
          database: "NEXUS_DATAPLATFORM"
          schema: "P_MVPD"
          stg_table: "P_NEXUS_MVPD_SPECTRUM_STG"
          pds_table: "P_NEXUS_MVPD_SPECTRUM"
          load_staging_table_sql: "snowflake/p_nexus_mvpd_spectrum_stg.sql"
          load_main_table_sql: "snowflake/p_nexus_mvpd_spectrum.sql"
          stage_name: "NEXUS_MVPD_SPECTRUM_PRD"
          folderpath : "preprocessing"
          snowflake_aggregation_tables:
            mvpd_dma: "snowflake/p_nexus_mvpd_spectrum_dma_agg.sql"
            mvpd_network: "snowflake/p_nexus_mvpd_spectrum_network_agg.sql"
            mvpd_lineitem: "snowflake/p_nexus_mvpd_spectrum_line_item_agg.sql"

      
  orchestration:
    schedule: "0 8 * * *"